version: "3.7"

x-petaconfig:
  &petalinux-config
  environment:
    - USER
    - TERM
    - http_proxy
    - https_proxy
  working_dir: "/home/${USER}/workspace/${PETALINUX_VER}"
  volumes:
    - "./workspace/${PETALINUX_VER}:/home/${USER}/workspace/${PETALINUX_VER}"

services:
  petalinux:
    <<: *petalinux-config
    image: petalinux:${PETALINUX_VER}-slim
    hostname: petalinux-${PETALINUX_VER}-slim

  petalinux-original:
    <<: *petalinux-config
    image: petalinux:${PETALINUX_VER}-original
    hostname: petalinux-${PETALINUX_VER}-original

# vim: set expandtab shiftwidth=0 tabstop=2 :
