version: "3.7"

x-args:
  &args
  USER:
  baseimage:
  http_proxy:
  https_proxy:

x-build-common:
  &build-common
  context: .
  network: nw

x-build-petalinux:
  &build-petalinux
  <<: *build-common
  dockerfile: Dockerfile.petalinux
  args:
    <<: *args
    PETALINUX_VER:

x-build-vivado:
  &build-vivado
  <<: *build-common
  dockerfile: Dockerfile.vivado
  args:
    <<: *args
    VIVADO_VER:

services:
  petalinux:
    build:
      <<: *build-petalinux
      target: petalinux-slim

  petalinux-original:
    build:
      <<: *build-petalinux
      target: petalinux-original

  vivado:
    build:
      <<: *build-vivado
      target: vivado-slim

  vivado-original:
    build:
      <<: *build-vivado
      target: vivado-original

  repository:
    image: nginx:alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    networks:
      - nw

networks:
  nw:
    name: nw

# vim: set expandtab shiftwidth=0 tabstop=2 :
