version: "3.7"

x-build-common:
  &build-common
  context: .
  network: nw
  args:
    - USER
    - baseimage
    - http_proxy
    - https_proxy

x-build-petalinux:
  &build-petalinux
  <<: *build-common
  dockerfile: Dockerfile.petalinux
  args:
    - PETALINUX_VER

services:
  petalinux:
    build:
      <<: *build-petalinux
      target: petalinux-slim

  petalinux-original:
    build:
      <<: *build-petalinux
      target: petalinux-original

  repository:
    image: nginx:alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    networks:
      - nw

networks:
  nw:
    name: nw

# vim: set expandtab shiftwidth=0 tabstop=2 :
