version: "3.7"

x-environment:
  &environment
  USER:
  TERM:
  http_proxy:
  https_proxy:

x-config-petalinux:
  &config-petalinux
  environment:
    <<: *environment
  working_dir: "/home/${USER}/workspace/${PETALINUX_VER}"
  volumes:
    - "./workspace/${PETALINUX_VER}:/home/${USER}/workspace/${PETALINUX_VER}"

x-config-vivado:
  &config-vivado
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}/workspace/${VIVADO_VER}"
  volumes:
    - "./workspace/${VIVADO_VER}:/home/${USER}/workspace/${VIVADO_VER}"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

x-config-vitis:
  &config-vitis
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}/workspace/${VITIS_VER}"
  volumes:
    - "./workspace/${VITIS_VER}:/home/${USER}/workspace/${VITIS_VER}"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

services:
  petalinux:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-slim
    hostname: petalinux-${PETALINUX_VER}-slim

  petalinux-original:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-original
    hostname: petalinux-${PETALINUX_VER}-original

  vivado:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-slim
    hostname: vivado-${VIVADO_VER}-slim

  vivado-original:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-original
    hostname: vivado-${VIVADO_VER}-original

  vitis:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-slim
    hostname: vitis-${VITIS_VER}-slim

  vitis-original:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-original
    hostname: vitis-${VITIS_VER}-original

# vim: set expandtab shiftwidth=0 tabstop=2 :
