version: "3.7"

services:
  petalinux:
    image: petalinux:${PETALINUX_VER}-slim
    environment:
      - USER
      - TERM
      - DISPLAY
      - http_proxy
      - https_proxy
    working_dir: "/home/${USER}/workspace/${PETALINUX_VER}"
    volumes:
      - "./workspace/${PETALINUX_VER}:/home/${USER}/workspace/${PETALINUX_VER}"

# vim: set expandtab shiftwidth=0 tabstop=2 :
