version: "3.7"

services:
  petalinux:
    image: petalinux:${PETALINUX_VER}-slim
    environment:
      - USER
      - TERM
      - DISPLAY
      - http_proxy
      - https_proxy

# vim: set expandtab shiftwidth=0 tabstop=2 :
