version: "3.7"

x-common:
  &common
  init: true

x-environment:
  &environment
  USER:
  USERS:
  TERM:
  http_proxy:
  https_proxy:

x-config-vivado:
  &config-vivado
  <<: *common
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}"
  volumes:
    - "./workspace/${VIVADO_VER}:/home"
    - "etc-vivado:/etc"
    - "/etc/localtime:/etc/localtime:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

x-config-vitis:
  &config-vitis
  <<: *common
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}"
  volumes:
    - "./workspace/${VITIS_VER}:/home"
    - "etc-vitis:/etc"
    - "/etc/localtime:/etc/localtime:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

x-config-petalinux:
  &config-petalinux
  <<: *common
  environment: *environment
  working_dir: "/home/${USER}"
  volumes:
    - "./workspace/${PETALINUX_VER}:/home"
    - "etc-petalinux:/etc"
    - "/etc/localtime:/etc/localtime:ro"

services:
  vivado-standard:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-standard
    hostname: vivado-${VIVADO_VER}-standard
    profiles: [non-default]

  vivado-slim:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-slim
    hostname: vivado-${VIVADO_VER}-slim
    profiles: [non-default]

  vivado-daemon:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-daemon
    hostname: vivado-${VIVADO_VER}-daemon
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vivado-${VIVADO_VER}

  vitis-standard:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-standard
    hostname: vitis-${VITIS_VER}-standard
    profiles: [non-default]

  vitis-slim:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-slim
    hostname: vitis-${VITIS_VER}-slim
    profiles: [non-default]

  vitis-daemon:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-daemon
    hostname: vitis-${VITIS_VER}-daemon
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vitis-${VITIS_VER}

  petalinux-standard:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-standard
    hostname: petalinux-${PETALINUX_VER}-standard
    profiles: [non-default]

  petalinux-slim:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-slim
    hostname: petalinux-${PETALINUX_VER}-slim
    profiles: [non-default]

  petalinux-daemon:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-daemon
    hostname: petalinux-${PETALINUX_VER}-daemon
    restart: unless-stopped
    networks:
      default:
        aliases:
          - petalinux-${PETALINUX_VER}

  frontend:
    <<: *common
    environment: *environment
    volumes:
      - "etc-frontend:/etc"
      - "home-frontend:/home"
    image: xilinx-frontend
    hostname: xilinx-frontend
    restart: unless-stopped
    networks:
      default:
        aliases:
          - frontend
    ports:
      - "10022:22"
    depends_on:
      - vivado-daemon
      - vitis-daemon
      - petalinux-daemon

volumes:
  etc-vivado:
  etc-vitis:
  etc-petalinux:
  etc-frontend:
  home-frontend:

# vim: set expandtab shiftwidth=0 tabstop=2 :
