version: "3.7"

x-args:
  &args
  USER:
  baseimage:
  http_proxy:
  https_proxy:

x-build-common:
  &build-common
  context: .
  network: nw

x-build-vivado:
  &build-vivado
  <<: *build-common
  dockerfile: Dockerfile.vivado
  args:
    <<: *args
    VIVADO_VER:

x-build-vitis:
  &build-vitis
  <<: *build-common
  dockerfile: Dockerfile.vitis
  args:
    <<: *args
    VITIS_VER:

x-build-petalinux:
  &build-petalinux
  <<: *build-common
  dockerfile: Dockerfile.petalinux
  args:
    <<: *args
    PETALINUX_VER:

services:
  vivado-original:
    build:
      <<: *build-vivado
      target: vivado-original

  vivado-slim:
    build:
      <<: *build-vivado
      target: vivado-slim

  vivado-daemon:
    build:
      <<: *build-vivado
      target: vivado-daemon

  vitis-original:
    build:
      <<: *build-vitis
      target: vitis-original

  vitis-slim:
    build:
      <<: *build-vitis
      target: vitis-slim

  vitis-daemon:
    build:
      <<: *build-vitis
      target: vitis-daemon

  petalinux-original:
    build:
      <<: *build-petalinux
      target: petalinux-original

  petalinux-slim:
    build:
      <<: *build-petalinux
      target: petalinux-slim

  petalinux-daemon:
    build:
      <<: *build-petalinux
      target: petalinux-daemon

  repository:
    image: nginx:alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    networks:
      - nw

networks:
  nw:
    name: nw

# vim: set expandtab shiftwidth=0 tabstop=2 :
