version: "3.7"

x-environment:
  &environment
  USER:
  TERM:
  http_proxy:
  https_proxy:

x-config-vivado:
  &config-vivado
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}"
  init: true
  volumes:
    - "./workspace/${VIVADO_VER}:/home/${USER}"
    - "/etc/localtime:/etc/localtime:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

x-config-vitis:
  &config-vitis
  environment:
    <<: *environment
    DISPLAY:
  working_dir: "/home/${USER}"
  init: true
  volumes:
    - "./workspace/${VITIS_VER}:/home/${USER}"
    - "/etc/localtime:/etc/localtime:ro"
    - "/tmp/.X11-unix:/tmp/.X11-unix"

x-config-petalinux:
  &config-petalinux
  environment:
    <<: *environment
  working_dir: "/home/${USER}"
  init: true
  volumes:
    - "./workspace/${PETALINUX_VER}:/home/${USER}"
    - "/etc/localtime:/etc/localtime:ro"

services:
  vivado-standard:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-standard
    hostname: vivado-${VIVADO_VER}-standard

  vivado-slim:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-slim
    hostname: vivado-${VIVADO_VER}-slim

  vivado-daemon:
    <<: *config-vivado
    image: vivado:${VIVADO_VER}-daemon
    hostname: vivado-${VIVADO_VER}-daemon
    restart: unless-stopped
    ports:
      - "10022:22"

  vitis-standard:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-standard
    hostname: vitis-${VITIS_VER}-standard

  vitis-slim:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-slim
    hostname: vitis-${VITIS_VER}-slim

  vitis-daemon:
    <<: *config-vitis
    image: vitis:${VITIS_VER}-daemon
    hostname: vitis-${VITIS_VER}-daemon
    restart: unless-stopped
    ports:
      - "10122:22"

  petalinux-standard:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-standard
    hostname: petalinux-${PETALINUX_VER}-standard

  petalinux-slim:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-slim
    hostname: petalinux-${PETALINUX_VER}-slim

  petalinux-daemon:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-daemon
    hostname: petalinux-${PETALINUX_VER}-daemon
    restart: unless-stopped
    ports:
      - "10222:22"

# vim: set expandtab shiftwidth=0 tabstop=2 :
