version: "3.7"

x-args:
  &args
  USER:
  baseimage:
  http_proxy:
  https_proxy:

x-build-common:
  &build-common
  context: .
  network: build

x-build-vivado:
  &build-vivado
  <<: *build-common
  dockerfile: Dockerfile.vivado
  args:
    <<: *args
    VIVADO_VER:

x-build-vitis:
  &build-vitis
  <<: *build-common
  dockerfile: Dockerfile.vitis
  args:
    <<: *args
    VITIS_VER:

x-build-petalinux:
  &build-petalinux
  <<: *build-common
  dockerfile: Dockerfile.petalinux
  args:
    <<: *args
    PETALINUX_VER:

x-build-sdk:
  &build-sdk
  <<: *build-common
  dockerfile: Dockerfile.sdk
  args: *args

x-build-frontend:
  &build-frontend
  <<: *build-common
  dockerfile: Dockerfile.frontend
  args: *args

services:
  vivado-standard:
    build:
      <<: *build-vivado
      target: vivado-standard

  vivado-slim:
    build:
      <<: *build-vivado
      target: vivado-slim

  vivado-daemon:
    build:
      <<: *build-vivado
      target: vivado-daemon

  vitis-standard:
    build:
      <<: *build-vitis
      target: vitis-standard

  vitis-slim:
    build:
      <<: *build-vitis
      target: vitis-slim

  vitis-daemon:
    build:
      <<: *build-vitis
      target: vitis-daemon

  petalinux-standard:
    build:
      <<: *build-petalinux
      target: petalinux-standard

  petalinux-slim:
    build:
      <<: *build-petalinux
      target: petalinux-slim

  petalinux-daemon:
    build:
      <<: *build-petalinux
      target: petalinux-daemon

  sdk-standard:
    build:
      <<: *build-sdk
      target: sdk-standard

  sdk-daemon:
    build:
      <<: *build-sdk
      target: sdk-daemon

  frontend:
    build:
      <<: *build-frontend
      target: sshd

  repository:
    image: nginx:alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    networks:
      - build

networks:
  build:
    name: build

# vim: set expandtab shiftwidth=0 tabstop=2 :
