version: "3.7"

x-config-common:
  &config-common
  environment:
    - USER
    - TERM
    - http_proxy
    - https_proxy

x-config-petalinux:
  &config-petalinux
  <<: *config-common
  working_dir: "/home/${USER}/workspace/${PETALINUX_VER}"
  volumes:
    - "./workspace/${PETALINUX_VER}:/home/${USER}/workspace/${PETALINUX_VER}"

services:
  petalinux:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-slim
    hostname: petalinux-${PETALINUX_VER}-slim

  petalinux-original:
    <<: *config-petalinux
    image: petalinux:${PETALINUX_VER}-original
    hostname: petalinux-${PETALINUX_VER}-original

# vim: set expandtab shiftwidth=0 tabstop=2 :
